-module(euler_two).
-export([euler/1]).

% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
%	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

euler(Max) ->
	solve(Max, 1, 1, 0).

solve(Max, Current, Prev, Total) ->
if
    Current > Max ->
        Total;
    Current rem 2 == 0 ->
        solve(Max, Current+Prev, Current, Total+Current);
    true ->
        solve(Max, Current+Prev, Current, Total)
end.
